---
title: "Flow of Questionnaires"
---

```{r options_communes, include=FALSE}
source("options_communes.R")
```

<div class="important">
This chapter is not written yet.
</div>

The Assessment includes 3 questionnaires: one for the household level (that includes specific questions depending on the Household profile), one at the Key informant Level and a series of open questions for Focus Group Discusssions. 

## key Informant level
The following modules will be included in the Protection Assessment at the key Informant level:


## Household Level
The following modules will be included in the Protection Assessment at the Household level:

### Questionnaire Componnent for Household Representative
* Profile of Household Members
* Education
* Child Labour
* Civil Documentation
* Property 
* accomodation Conditions

### Questionnaire Componnent for Individual Women
* Access to Mass Media and Use of Information and Communication Technology
* Attitudes toward Domestic Violence
* Marriage/Union
* Intention

### Questionnaire Componnent for Individual Men
* Access to Mass Media and Use of Information and Communication Technology
* Attitudes toward Domestic Violence	Marriage/Union
* Intention

### Questionnaire Componnent for Children & Youth
* Birth Registration
* School attendance
* Early Marriage


## Focus Group Discussions Level
