---
title: "Guidelines for questionnaire customisation"
---

```{r options_communes, include=FALSE}
source("options_communes.R")
```

<div class="note">

</div>


## What is "customisation"?

Customisation (or adaptation) refers to the process during which the standard Protection Assessment questionnaires are tailored to the population/context where a the Asessment is being conducted (that is, a national assessment, or a assessment conducted for a population group or for a selected area within a country), using standard principles and approaches, while maintaining global comparability of the indicators that will be derived from the collected data.

The customisation process is by no means an easy and straightforward one. Without a detailed understanding of all the standard tools and of the general principles and recommendations, customisation of questionnaires should not be attempted at country level without the assistance of an expert. During the customisation process, it is also absolutely critical that lessons learned from previous data collection activities are used effectively, and wherever necessary, tools are tested before final decisions are made. Testing may include organized pre-testing, field testing, piloting, and in some cases, cognitive testing. Analysis of raw data from previous assessment and data collection activities, as well as results from these efforts should also be undertaken for successful customisation of standard questionnaires.

## What kind of "Customisation"?

Customisation of the Questionnaires, Modules, Questions, and Response Categories is necessary for at least two basic reasons:
 * 	No single country/survey is expected or recommended to use all of the modules in standard questionnaires
 * 	No single standard questionnaire can accurately represent all human experience around the globe


Customisation covers the following types of changes to the standard protection questionnaires:
 * 	Country-/assessment-specific modifications to already existing standard questions and response codes,
 * 	Deletions from the standard questionnaires, and
 * 	Additions to the standard questionnaires. 

## Modification

Certain parts of the standard questionnaires must be modified. Indeed, in several instances, the standard questionnaires include clear directives that a change or modification needs to be made. These cases are indicated using text such as  “insert local name". Similarly, response categories that require customisation are also indicated. 

## Deletion
No assessment is recommended to retain all of the modules and questions of the standard protection questionnaires. First, there will always be some topics that will not be relevant in certain countries or regions. Second, decisions on the content of any assessment will ideally be made as a result of a thorough data gap assessment, generally based on the required analysis, and, for example, when information is available from other recent data sources, certain modules or sets of questions will be dropped. The process and analysis involved in a comprehensive data needs assessment will vary, but is a crucial step in determining the content of the assessment.

Determining what to exclude from the assessment is a balancing act that should take data needs into account, but also learn from countless experiences of data quality issues as a result of overloaded questionnaires. Country priorities will guide decisions, but may also work against achieving an optimum questionnaire size if negotiations turn more political than technical.

A final consideration will also rest with the ability to implement an adequate sample size, as this is often constrained by budget on one hand and on the other the known data quality issues associated with large sample sizes. For instance, some indicators are difficult to measure in low fertility settings, demanding higher sample sizes or complicated sample designs. Unless such issues can be technically addressed, the exclusion of such indicators may be necessary.

## Addition

Some Protection Asessment may also add topics, modules and questions which are not already in the standard questionnaires. These could include additions that the standard questionnaires already point to (for example, adding household assets to the list already in the questionnaires), or additions of modules or sets of questions that are not covered in the standard questionnaires. 

From the onset of considerations of what could be added in, you should know that this will affect the technical support available as well as require changes and considerations throughout the package of tools available, from sampling, training, instructions, and data entry application to tabulations and reporting.

As with the above exercise of deleting from the questionnaires, your entry point should be the indicator list or, alternatively, the tabulation plan. Questionnaire design is secondary to the need for precise information on what such proposed additions would be measuring and how such would be presented.

Only questions that are previously well-tested and validated should be included. Questions are often imported from other household surveys that have been conducted in the country. This does not necessarily mean that they are validated nor does it mean that such questions can work within the frame of a Protection Assessment.

If additions are made, please ensure that formatting and coding follow the rules in place for the standard questionnaires. For entirely new topics it may be useful to build a new module and in other cases you will need to append to an existing module or insert within the existing flow.


## Rules and Useful Tips for Customisation

While customising the survey questionnaires where a translation is involved, it is recommended that you:

 * 	Check percentages of population speaking different local languages and consider translation to all major languages spoken among the survey population
 * 	Check previous surveys to see how the customisation was done 
 * 	Consider the use of a language that could be understood by everyone
 * 	Pre-test the translated version to make sure that the questions are understood and the response categories are meaningful
 * 	Customise to country/survey needs, but do not compromise global comparability.
 * 	For implementation or questionnaire flow, Check for all skips
 * 	For data analysis, Check for the indicators you need and ensure that all required questions to calculate the indicators are included 
 * 	Always assess the implications of changes, in terms of (a) all other survey tools and (b) the technical aspects/validity; test rigorously, document, and modify all other relevant survey tools accordingly.
