---
  title: "Protection Topics"
---
  
  ```{r options_communes, include=FALSE}
source("options_communes.R")
```

<div class="important">

Vulnerability level for a specific risk =
function(risk **occurrence**) +
function(**exposure** to risk of basic right violation) +
function(**coping capacity** before or after violation)

wich helps to distinguish 

Protection activities for UNHCR = 
Prevent occurrence of basic right violation event (**Environment Building actions**) && 
Limit the effects of violation events consequences (**Remedial actions**) &&
Respond to basic right violation event  (**Responsive actions**)
</div>

Protection analysis is therefore linked to specific events linked to specific Right groups defined by UNHCR Result Based management.

Rights Group                                    | Basic right type                       | Violation event
----------------------------------------------- |--------------------------------------- | ------------- 
__Favourable Protection Environment__           | Non-refoulement                        | Non-admission, Refoulement
-                                               | No discrimination                      | Detention
-                                               | Freedom of movement                    | Eviction, deportation
__Fair Protection Processes and Documentation__ | Documentation                          | No issuance/renewal of residency
-                                               | Right to a nationality                 | Birth Registration
__Community Empowerment and Self Reliance__     | Livelihood                             | Negative coping mechanism (Prostitution, child labour, early marriage, begging, stealing,.)
-                                               | Peaceful co-existence                  | Intercommunity violence
__Basic Needs and Essential Services__          | Education                              | Children out of school
-                                               | Food                                   | Malnutrition
-                                               | Social & economic rights               | Non access to services (healh, schools, MPSS)
-                                               | Housing, Wash & Shelter                | Sub standard living conditions
__Security from Violence and Exploitation__     | Age, gender and diversity mainstreaming| Sex & Gender based violence, child abuses


<div class="note">
On each topic, the protection assessment should allow to identify the affected population’s vulnerability profile:

* Capacities and capabilities in order to define __criticality__ 
* Threat  in terms of occurence in order to define __magnitude__ 
* Threat  in terms of exposure in order to define __severity__


The vulnerability profile (combination of criticality/magnitude/severity) for each topic will allow to prioritise the relevant activities. 
</div>

## Favourable Protection Environment    

List of analysis modules

* Protection-sensitive border mechanism
* Counselling & Legal aid
* Freedom of movement & Detention
* Multiple Displacement & Movement

## Fair Protection Processes and Documentation 

List of analysis modules

* Birth Registration
* Civil status documentation
* Family re-unification
* Refugee registration
* Risk of eviction

## Community Empowerment and Self Reliance 

List of analysis modules:

* Social cohesion
* Type of assistance received
* Housing, shelter & wash conditions
* Employment & livelihood
* Child Labour
* Assets & Budget

## Basic Needs and Essential Services 

List of analysis modules:

* Refugees with specific needs 
* Assistance received
* Negative coping mechanism
* Food security
* Access to health services
* Education & Out of School Children

## Security from Violence and Exploitation

List of analysis modules:

* Sexual Harassment & Violence (Rape) 
* Harassment between youth
* Gender inequality
* Domestic Violence (Parental stress, Isolation at home)
* Forced and early marriage
* Violence among children
* Armed recruitment
* Harassment & Violence towards LGBTI
* Security & Civil violence


## Context information


* Metadata
* Enumerator
* Address
* Consent
* Household information
* Self-expressed Needs
* Subjective Evaluation
* Referral
* Notes



