---
title: "Sample size & Weight Calculation"
---

```{r options_communes, include=FALSE}
source("options_communes.R")
```

## Defining sample size

If you need a purely random sample, the size of the sample if a calculation that takes 3 variables:

*	Size of the full population
*	Confidence level: for what proportion of the population you want to get the right estimation (usually either 90%, 95% or 99%) 
*	Error Margin (or confidence interval): How much error are you willing to tolerate for each questions? i.e. + or – your estimated ratio for each questions on the top of the confidence interval (usually either 5%, 2% or 1%)

There are [online calculator](https://www.surveymonkey.com/mp/sample-size-calculator/) for this.  


For 400,000 Syrians  | 	5% error margin 	| 		2% error margin		| 	1% error margin
---------------------|--------------------|-----------------------| ----------------- 
90% Confidence level |	272               |	1694                  |	6692
95% Confidence level |	384             	| 2387                 	| 9379
99% Confidence level |	662               |	4105                  |	15929


			
For 150,000 Afghans	| 	5% error margin 	| 		2% error margin		| 	1% error margin
--------------------|---------------------|-----------------------|------------------ 
90% Confidence level|	272                 |	1682                  |	6511
95% Confidence level|	383                 |	2363                  |	9026
99% Confidence level|	661                 |	4036                  |	14937


Usually the decision on the right confidence level and error margin to be selected is also influenced by cost implication and the final usage of the figures that is looked for.


## Sample universe

### In refugee Context

Data is coming from proGres


### In IDP context

Data is coming from a *Displacement Tracking Matrix*

## Sampling strategy


### Convenience sampling: 
It is a frequently used method in emergency situations. It relies on sampling those respondents who are easiest to access. For example those who have settled along roadsides, or near the administrative center of the returnee settlement, etc. The danger with this type of monitoring is that it will often lead to biased results as the sample may not be representative of the majority, i.e. those with the most resources or power are often the ones who settle in the most easily accessible areas.

### Purposive sampling
It is based on previous knowledge about who might be able to provide valuable or specific information.  The sampling of children or women, for example, is a type of purposive sampling 


### Random sampling

### Sonowball sampling

### Purposive sampling using strata


## Sample Weight

Over-sampling in regions with small populations ensures that they have a large enough sample to be representative. Under-sampling is done in regions with large populations to save costs. Sample weights are mathematical adjustments applied to the data to correct for over-sampling, under-sampling, and different response rates to the survey in different regions.

### How are the oversampled/undersampled areas corrected in data analysis?

The samples are designed to permit data analysis of regional subsets within the sample population. When the expected number of cases for some of these regions is too small for analysis, it is necessary to oversample those areas. When the expected number of cases for some of these regions is unnecessarily large, those areas may be undersampled to accommodate logistical or budgetary constraints.

During analysis, it is then necessary to "weight down" the oversampled areas and "weight up" the undersampled areas. The developing of the sampling weights has taken this factor into account. Always use the weight variable found in the DHS data set. Even in surveys that come from a self-weighting sample, it is still necessary to use the sampling weights in analysis because the response behavior may differ by response groups.

### What does it mean to normalize the weights?

After the weights are initially calculated, they are normalized, or standardized, by dividing each weight by the average of the initial weights (equal to the sum of the initial weight divided by the sum of the number of cases) so that the sum of the normalized/standardized weights equals the sum of the cases over the entire sample. The standardization is done separately for each weight for the entire sample.  

The entire set of household sample weights is multiplied by a constant, thus, the total weighted number of households equals the total unweighted number of households at the national level.

Individual sample weights are normalized separately for women and men. Thus, the total weighted number of women equals the total unweighted number of women, and the total weighted number of men equals the total unweighted number of men. Women and men are normalized separately because all non-HIV calculations are performed on women and men separately. We do not provide survey estimates on the joint population of women and men combined for anything other than HIV prevalence.