---
title: "Sampling"
---

```{r options_communes, include=FALSE}
source("options_communes.R")
```


<div class="important">

The sampling strategy is constrainted by both available budget, field accessibility and time. The sampling approach reflects a trade off between representativity of the results, rapid delivery and  


 
</div>


## Sampling strategy

Sampling strategy can be either probabilistic or non-probabilistic.

### Non-probabilistic approaches

Non-probabilistic approaches are usually **favored during the emergency phase** where both time and field access represent the main challenge. 

#### Convenience sampling 
It is a frequently used method in emergency situations. It relies on sampling those respondents who are easiest to access.

Practically speaking those couldd be either:
  * key Informant that are ready to report by themself
  * Individuals or household among those who have settled along roadsides, or who present themselves to administrative center of the returnee settlement or the assistance desk etc. 


 * Advantages: Easy and quick to implement, especially when time and access are the main constraints.

 * Disadvantage: The danger with this type of data collection approach is that it will often lead to biased results as the sample may not be representative of the majority, i.e. those with the most resources or power are often the ones who settle in the most easily accessible areas.


#### Snowball sampling

Snowball sampling (or [chain sampling, chain-referral sampling, referral sampling](https://en.wikipedia.org/wiki/Snowball_sampling)) is a non-probability sampling technique where existing study subjects recruit future subjects from among their acquaintances. This technique is subject to numerous biases. For example, people who have many friends are more likely to be recruited into the sample. 

 * Advantages: Useful when targeting specific groups that might be difficult to reach (hidden population).

 * Disadvantage: This approach might underweight the most vulnerable individuals.

#### Purposive sampling
It is based on previous knowledge about who might be able to provide valuable or specific information. It uses the judgement of community representatives, project staff or assessors to select typical locations and/or informants. The sampling of children or women, for example, is a type of purposive sampling.

Purposive sampling can also be done through Key Informant.

 * Advantages: Moderately rigorous if well and clear criteria for sampling are followed. Useful when targeting specific groups of affected population or specific affected areas. Less time consuming and less expensive than representative sampling.

 * Disadvantage: Generalisations are biased and not recommended. Samples are not representative of population due to subjectivity of respondents.

The risk of loosing certain componnent of the population can be addressed by defining strata within the purposive sample.


### Probalistics approaches

Whenever the situation is becoming more **protracted**, probabilistic approaches should be favored. They will allow to generate more reliable results.

#### Respondent-driven sampling -RDS

A declination of snowball sampling is the [Respondent-driven sampling -RDS](http://www.respondentdrivensampling.org/) approach. It combines "snowball sampling" with a mathematical model that weights the sample to compensate for the fact that the sample was collected in a non-random way. As such it can be classified as probabilistic approach. The advantage is that seeds selection is specific and does not require sample frame.

While data requirements for RDS analysis are minimal, there are three pieces of information which are essential for analysis (RDS analysis CANNOT BE PERFORMED without these fields for each respondent):

* Personal Network Size (Degree) - Number of people the respondent knows within the target population. 
* Respondent's Serial Number - Serial number of the coupon the respondent was recruited with. 
* Respondent's Recruiting Serial Numbers - Serial numbers from the coupons the respondent is given to recruit others. 



#### Time-Location Sampling

The Time-Location Sampling (TLS) approach can be used when the goal is to have a representation of population in movement. The idea and the assumption is to sample persons at locations and at time at which they may be found. 

Time-location sampling is used to sample a population for which a sampling frame cannot be constructed but locations are known at which the population of interest can be found, or for which it is more efficient to sample at these locations. As such the approach is likely appropriate when the survey is taking place at a  **border**. 

More practical guidelines for TLS are available in a dedicated [Resource Guide TLS](http://globalhealthsciences.ucsf.edu/sites/default/files/content/pphg/surveillance/modules/global-trainings/tls-res-guide-2nd-edition.pdf) and some application on Border Monitoring for [tourism](http://meetings.sis-statistica.org/index.php/sm/sm2012/paper/viewFile/2180/149) or [illegal migrants](https://books.google.jo/books?id=Gz9eAgAAQBAJ&pg=PA53&lpg=PA53&dq=Border+surveys+and+Time+Location+Sampling&source=bl&ots=6i5IgC-2Mb&sig=P3CdG8-LvC0Y_LCK-MZ047gAJNQ&hl=en&sa=X&redir_esc=y#v=onepage&q=Border%20surveys%20and%20Time%20Location%20Sampling&f=false). 


#### Random sampling 

If you need a purely random sample, the size of the sample is a calculation that takes 3 variables:

*	Size of the full population
*	Confidence level: for what proportion of the population you want to get the right estimation (usually either 90%, 95% or 99%) 
*	Error Margin (or confidence interval): How much error are you willing to tolerate for each questions? i.e. + or – your estimated ratio for each questions on the top of the confidence interval (usually either 5%, 2% or 1%)

There are [online calculator](https://www.surveymonkey.com/mp/sample-size-calculator/) for this.  


For 400,000 Syrians  | 	5% error margin 	| 		2% error margin		| 	1% error margin
---------------------|--------------------|-----------------------| ----------------- 
90% Confidence level |	272               |	1694                  |	6692
95% Confidence level |	384             	| 2387                 	| 9379
99% Confidence level |	662               |	4105                  |	15929


			
For 150,000 Afghans	| 	5% error margin 	| 		2% error margin		| 	1% error margin
--------------------|---------------------|-----------------------|------------------ 
90% Confidence level|	272                 |	1682                  |	6511
95% Confidence level|	383                 |	2363                  |	9026
99% Confidence level|	661                 |	4036                  |	14937


Usually the decision on the right confidence level and error margin to be selected is also influenced by cost implication and the final usage of the figures that is looked for.



#### Stratified sampling  

#### Cluster sampling 



## Statistical Biais

### Selection Bias
Some groups are more or less likely to be selected in the sample
Who might we miss when contacting people on the phone:
Just people who are not here anymore?
Random people who lost/changed their phone
Vulnerable people who had to move, didn’t report their change of phone number because of lack of access to services…

### Declaration Bias
Incentives/Fear make people declare information inaccurately
For instance:
Fear associated with Legal obligations
Reporting Financial Issues in hope to get support


## Sample size


In the case of Desk interview or key Informant, the more observation the better. 

Some kind of [credibility scoring](http://iomiraqdtm.info/Downloads/00-%20DTM%20Methodology%20Documents/DTM_LA_Credibility_Scoring_Methodology.pdf) can be obtained for each locations based on a review of the key informant. 



### In refugee Context

Data is coming from proGres

### In IDP context

Data is coming from a *Displacement Tracking Matrix*


## Sample Weight

Over-sampling in regions with small populations ensures that they have a large enough sample to be representative. Under-sampling is done in regions with large populations to save costs. Sample weights are mathematical adjustments applied to the data to correct for over-sampling, under-sampling, and different response rates to the survey in different regions.

### How are the oversampled/undersampled areas corrected in data analysis?

The samples are designed to permit data analysis of regional subsets within the sample population. When the expected number of cases for some of these regions is too small for analysis, it is necessary to oversample those areas. When the expected number of cases for some of these regions is unnecessarily large, those areas may be undersampled to accommodate logistical or budgetary constraints.

During analysis, it is then necessary to "weight down" the oversampled areas and "weight up" the undersampled areas. The developing of the sampling weights has taken this factor into account. Always use the weight variable found in the DHS data set. Even in surveys that come from a self-weighting sample, it is still necessary to use the sampling weights in analysis because the response behavior may differ by response groups.

### What does it mean to normalize the weights?

After the weights are initially calculated, they are normalized, or standardized, by dividing each weight by the average of the initial weights (equal to the sum of the initial weight divided by the sum of the number of cases) so that the sum of the normalized/standardized weights equals the sum of the cases over the entire sample. The standardization is done separately for each weight for the entire sample.  

The entire set of household sample weights is multiplied by a constant, thus, the total weighted number of households equals the total unweighted number of households at the national level.

Individual sample weights are normalized separately for women and men. Thus, the total weighted number of women equals the total unweighted number of women, and the total weighted number of men equals the total unweighted number of men. Women and men are normalized separately because all non-HIV calculations are performed on women and men separately. We do not provide survey estimates on the joint population of women and men combined for anything other than HIV prevalence.
